### ISSUE TITLE
[Bug] Build error in Arch Linux

### ISSUE THREAD

**Issue by zxp19821005** [talex-touch/talex-touch#57]
# TalexTouch

> Bug report template

## Type

Type: Build Error

## Environment

- My OS information: <Linux> <EndeavourOS 6.1.35-1-lts x86_64>
- My App information: TalexTouch <1.2> <OFFICIAL>

## Check your steps

- [x] I confirm that I have to fill in the content and correct
- [x] I confirm that I have seen no similar issues
- [x] I confirm that I described and illustrated as far as possible

## pnpm install
```
$ pnpm install
 WARN  deprecated electron-osx-sign@0.6.0: Please use @electron/osx-sign moving forward. Be aware the API is slightly different
 WARN  deprecated asar@3.2.0: Please use @electron/asar moving forward.  There is no API change, just a package name change
 WARN  deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
 WARN  deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
Downloading registry.npmmirror.com/element-plus/2.2.33: 7.83 MB/7.83 MB, done
Downloading registry.npmmirror.com/@swc/core-linux-x64-gnu/1.3.37: 14.9 MB/14.9 MB, done
Packages: +699
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /home/zxp-endeavouros/.local/share/pnpm/store/v3
  Virtual store is at:             node_modules/.pnpm
node_modules/vue-demi: Running postinstall script, done in 111ms
node_modules/@swc/core: Running postinstall script, done in 88ms
Progress: resolved 716, reused 454, downloaded 229, added 699, done
node_modules/electron: Running postinstall script, done in 7.9s
The integrity of 2220 files was checked. This might have caused installation to take longer.
Done in 16.2s
```

## pnpm run build
```
$ pnpm run build                  

> talex-touch@1.2.0 build /home/zxp-endeavouros/.cache/paru/clone/talex-touch-1.2.0
> electron-builder

  • electron-builder  version=23.6.0 os=6.1.35-1-lts
  • loaded configuration  file=/home/zxp-endeavouros/.cache/paru/clone/talex-touch-1.2.0/electron-builder.json5
  • writing effective config  file=release/1.2.0/builder-effective-config.yaml
  • packaging       platform=linux arch=x64 electron=23.1.2 appOutDir=release/1.2.0/linux-unpacked
  • downloading     url=https://npm.taobao.org/mirrors/electron/23.1.2/electron-v23.1.2-linux-x64.zip size=95 MB parts=8
┌────────────────────────────────────────────┐
│ New version of electron-builder available! │
│ Current Version: 23.6.0                    │
│ Latest Version: 24.4.0                     │
└────────────────────────────────────────────┘
  • downloaded      url=https://npm.taobao.org/mirrors/electron/23.1.2/electron-v23.1.2-linux-x64.zip duration=5.585s
  ⨯ Application entry file "dist/electron/main/index.js" in the "/home/zxp-endeavouros/.cache/paru/clone/talex-touch-1.2.0/release/1.2.0/linux-unpacked/resources/app.asar" does not exist. Seems like a wrong configuration.  failedTask=build stackTrace=Error: Application entry file "dist/electron/main/index.js" in the "/home/zxp-endeavouros/.cache/paru/clone/talex-touch-1.2.0/release/1.2.0/linux-unpacked/resources/app.asar" does not exist. Seems like a wrong configuration.
    at error (/home/zxp-endeavouros/.cache/paru/clone/talex-touch-1.2.0/node_modules/app-builder-lib/src/asar/asarFileChecker.ts:7:12)
    at Object.checkFileInArchive (/home/zxp-endeavouros/.cache/paru/clone/talex-touch-1.2.0/node_modules/app-builder-lib/src/asar/asarFileChecker.ts:31:11)
    at LinuxPackager.checkFileInPackage (/home/zxp-endeavouros/.cache/paru/clone/talex-touch-1.2.0/node_modules/app-builder-lib/src/platformPackager.ts:503:7)
    at LinuxPackager.sanityCheckPackage (/home/zxp-endeavouros/.cache/paru/clone/talex-touch-1.2.0/node_modules/app-builder-lib/src/platformPackager.ts:551:5)
    at LinuxPackager.doPack (/home/zxp-endeavouros/.cache/paru/clone/talex-touch-1.2.0/node_modules/app-builder-lib/src/platformPackager.ts:312:5)
    at LinuxPackager.pack (/home/zxp-endeavouros/.cache/paru/clone/talex-touch-1.2.0/node_modules/app-builder-lib/src/platformPackager.ts:136:5)
    at Packager.doBuild (/home/zxp-endeavouros/.cache/paru/clone/talex-touch-1.2.0/node_modules/app-builder-lib/src/packager.ts:441:9)
    at Object.executeFinally (/home/zxp-endeavouros/.cache/paru/clone/talex-touch-1.2.0/node_modules/builder-util/src/promise.ts:12:14)
    at Packager._build (/home/zxp-endeavouros/.cache/paru/clone/talex-touch-1.2.0/node_modules/app-builder-lib/src/packager.ts:376:31)
    at Packager.build (/home/zxp-endeavouros/.cache/paru/clone/talex-touch-1.2.0/node_modules/app-builder-lib/src/packager.ts:337:12)
    at Object.executeFinally (/home/zxp-endeavouros/.cache/paru/clone/talex-touch-1.2.0/node_modules/builder-util/src/promise.ts:12:14)
 ELIFECYCLE  Command failed with exit code 1.
```

Another Problem:
When I downloaded the [app.asar](https://github.com/talex-touch/talex-touch/releases/download/1.2.0/app.asar) and used the system electron to run,I got errors :
```
$ exec electron --no-sandbox ./app.asar
[TalexTouch-ErrorUnhandled] TypeError: Error processing argument at index 0, conversion failure from undefined
    at _.loadURL (node:electron/js2c/browser_init:2:85990)
    at s.loadURL (node:electron/js2c/browser_init:2:11275)
    at Ao (/home/zxp-endeavouros/.cache/paru/clone/app.asar/dist/electron/main/index.js:197:4216) Promise {
  <rejected> TypeError: Error processing argument at index 0, conversion failure from undefined
      at _.loadURL (node:electron/js2c/browser_init:2:85990)
      at s.loadURL (node:electron/js2c/browser_init:2:11275)
      at Ao (/home/zxp-endeavouros/.cache/paru/clone/app.asar/dist/electron/main/index.js:197:4216)
}
[162023:0625/125347.026915:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.DBus.StartServiceByName: object_path= /org/freedesktop/DBus: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
```

```
$ exec electron ./app.asar             
[TalexTouch-ErrorUnhandled] TypeError: Error processing argument at index 0, conversion failure from undefined
    at _.loadURL (node:electron/js2c/browser_init:2:85990)
    at s.loadURL (node:electron/js2c/browser_init:2:11275)
    at Ao (/home/zxp-endeavouros/.cache/paru/clone/app.asar/dist/electron/main/index.js:197:4216) Promise {
  <rejected> TypeError: Error processing argument at index 0, conversion failure from undefined
      at _.loadURL (node:electron/js2c/browser_init:2:85990)
      at s.loadURL (node:electron/js2c/browser_init:2:11275)
      at Ao (/home/zxp-endeavouros/.cache/paru/clone/app.asar/dist/electron/main/index.js:197:4216)
}
[162332:0625/125553.234114:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.DBus.StartServiceByName: object_path= /org/freedesktop/DBus: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
```
## Contact

@zxp19821005

**Comment by TalexDreamSoul** [comment]
I appreciate your feedback!

Here are some suggestions:

- The 1.2.0 version is outdated, advising you to use 2.0.0 reloaded!
- I will build it in EndeavourOS, but only in the 2.0.0 version.
- The second problem may be the difference between OS causes. I will soon screen them.

Additionally, the contact should be at us because it makes me earlier to know the issue!

Thanks!

**Comment by TalexDreamSoul** [comment]
## I have solved this problem

- **pnpm run build** is your network connection error, pls check it and try to use a proxy if necessary.
- **app.asar** may contain an error mapper URL or environment, try to rebuild in your OS pls, thanks!

However, thank you for your continuous support!
