### ISSUE TITLE
[Bug] 在启动过程中需要手动创建plugins文件夹

### ISSUE THREAD

**Issue by YunHerry** [talex-touch/talex-touch#9]
#### Describe the bug
在使用pnpm run dev的过程中,发生报错:
```
[WARN] PluginManager feedbacks a error!
Error: ENOENT: no such file or directory, scandir 'D:\Projects\talex-touch\talex-touch\plugins'
    at Object.readdirSync (node:fs:1405:3)
    at e.readdirSync (node:electron/js2c/asar_bundle:5:10830)
    at PluginManager.initial (D:\Projects\talex-touch\dist\electron\main\index.js:636:44)
    at createWindow (D:\Projects\talex-touch\dist\electron\main\index.js:997:25) {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'D:\\Projects\\talex-touch\\talex-touch\\plugins'
}
```
我在项目目录下的talex-touch目录下创建了plugins文件夹才能成功启动,否则将会呈现空白页面。

**Comment by TalexDreamSoul** [comment]
新版本已修复
Prefer details on [here](https://github.com/talex-touch/talex-touch/blob/master/electron/plugins/plugin-manager.ts#L26-L28)
